cd compose;go test;cd ..
cd actors/eureka;go test;cd ../..
cd actors/priamCassandra;go test;cd ../..
cd tooling/archaius;go test;cd ../..
cd tooling/architecture;go test;cd ../..
cd tooling/dhcp;go test;cd ../..
cd tooling/flow;go test;cd ../..
cd tooling/gotocol;go test;cd ../..
cd tooling/graphjson;go test;cd ../..
cd tooling/names;go test;cd ../..
cd tooling/ribbon;go test;cd ../..
cd tooling/usl;go test;cd ../..
