cd archaius;go test;cd ..
cd architecture;go test;cd ..
cd compose;go test;cd ..
cd dhcp;go test;cd ..
cd eureka;go test;cd ..
cd flow;go test;cd ..
cd gotocol;go test;cd ..
cd graphjson;go test;cd ..
cd names;go test;cd ..
cd priamCassandra;go test;cd ..
